sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t ahmedkerkeni/docker-react -f Dockerfile.dev .

script:
  - docker run ahmedkerkeni/docker-react npm run test -- --coverage

