language: generic 
services:
  - docker

before_install:
  - docker build -t ahmedkerkeni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahmedkerkeni/docker-react npm run test -- --coverage




